# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  main@v1:
    root: openapi/catalyst.yaml
rules:
  no-unused-components: warn
  # Disable linting rules that don't affect GitBook publishing
  security-defined: off
  operation-4xx-response: off
  no-invalid-media-type-examples: off
  no-invalid-schema-examples: off
theme:
  openapi:
    sideNavStyle: path-only
    htmlTemplate: ./docs/index.html
    theme:
      colors:
        primary:
          main: "#32329f"
