openapi: 3.0.3
info:
  title: API Specification for the Decentraland Catalyst Comms Service
  version: '1.0'
  description: >-      
     The current specification details the Comms service
  x-logo:
    url: 'https://cryptologos.cc/logos/decentraland-mana-logo.png'
  license:    
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
 
servers:
  - url: 'https://peer.decentraland.zone/comms'
    description: Catalyst Development instance
  - url: 'https://peer-testing.decentraland.org/comms'
    description: Catalyst Staging instance
  - url: 'https://peer.decentraland.org/comms'
    description: First production Catalyst node
tags:
  - name: Comms
    description: >- 
      Comms is comprised of two distinct modules: One for Catalyst server called "Lighthouse" and other for clients & 
      P2P network called "Peer Library".
      <br/>The Lighthouse is a server that tracks peers in different positions in order to enable them to make the 
      necessary connections. It also handles authentication.

paths:
  /config:
    $ref: 'paths/comms/comms@config.yaml'
  /islands:
    $ref: 'paths/comms/comms@islands.yaml'
  /islands/{islandId}:
    $ref: 'paths/comms/comms@islands@{islandId}.yaml'
  /peers: 
    $ref: 'paths/comms/comms@peers.yaml'
  /status:
    $ref: 'paths/comms/comms@status.yaml'
  