get:
  operationId: getConfig
  summary: Comms Service Configuration
  tags:
    - Comms
  description: Retrieves the Catalyst comms service settings
  responses:
    '200':
      description: Comms Service settings
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ../../components/schemas/comms/200-config.yaml
          examples:
            default:
              $ref: ../../components/examples/comms/200-config.json
put:
  operationId: updateConfig
  summary: Update Service Configuration
  tags:
    - Comms
  description: >- 
    Update Comms Service settings, this request requires you to send a body
    with a list of key/value pair specifying the new values for the service 
    properties and a signature to verify that you have sufficient permissions 
    in order to perform these updates.    
    The signer must be configured in the Catalyst Server through an Environment variable called 
    RESTRICTED_ACCESS_ADDRESS. 
    The signature is generated with the privateKey of the address using the following method
    https://github.com/pubkey/eth-crypto#sign
  requestBody:
    content:
      application/json:          
          schema:
            $ref: ../../components/schemas/comms/put-config.yaml
          examples:
            default:
              $ref: ../../components/examples/comms/put-config.json
  responses:
    '200':
      description: Settings updated successfully      
    '400':
      description: Bad Request 
      content:
        application/json:
          example: 'Expected array body with {key: string, value?: string} elements'
    '401':
      description: Unauthorized
      content:
        application/json:
          example: The signature is too old or too far in the future
