type: object
properties:
  config:
    type: array
    items:
      type: object
      properties:
        key:
          type: string
        value:
          type: number
  simpleSignature:
    type: object
    properties:
      signer:
        type: string
      signature:
        type: string
  timestamp:
    type: number