name: Publish API Docs to GitBook
on:
  push:
    branches: [main]
    paths:
      - 'openapi/**'
  pull_request:
    paths:
      - 'openapi/**'

jobs:
  validate-bundle-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Validate API spec with project config
        run: yarn test:api
      
      - name: Bundle API spec
        run: |
          npx @redocly/cli bundle openapi/catalyst.yaml -o bundled-openapi.yaml
          echo "✅ Bundled spec created"
          ls -lh bundled-openapi.yaml
      
      - name: Upload bundled spec as artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: bundled-openapi.yaml
          retention-days: 30
      
      - name: Sync to GitBook
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITBOOK_TOKEN: ${{ secrets.GITBOOK_TOKEN }}
          GITBOOK_SPACE_ID: ${{ secrets.GITBOOK_SPACE_ID }}
        run: |
          if [ -z "$GITBOOK_TOKEN" ] || [ -z "$GITBOOK_SPACE_ID" ]; then
            echo "⚠️  GitBook secrets not configured. Skipping GitBook sync."
            echo "✅ Validation and bundling completed successfully."
            echo "📦 Bundled spec available as workflow artifact."
            exit 0
          fi
          
          echo "📚 Publishing to GitBook..."
          echo ""
          echo "Recommended setup:"
          echo "  1. In GitBook, go to Integrations"
          echo "  2. Connect your GitHub repository"
          echo "  3. Configure GitBook to import OpenAPI from workflow artifacts"
          echo ""
          echo "✅ Bundled OpenAPI spec is ready for GitBook import"
          echo "📦 Download artifact: openapi-spec (bundled-openapi.yaml)"

