name: Publish API Docs to GitBook
on:
  push:
    branches: [main]
    paths:
      - 'openapi/**'
  pull_request:
    paths:
      - 'openapi/**'

jobs:
  publish-to-gitbook:
    uses: decentraland/platform-actions/.github/workflows/apps-docs.yml@main
    with:
      api-spec-file: 'openapi/catalyst.yaml'
      api-spec-name: 'catalyst-api'
      node-version: '20'
    secrets: inherit

