on:
  push:
    branches: [ main ]

name: Release and publish NPM package
jobs:

  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  release:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build-and-test
    if: ${{ success() }}
    steps:
      - uses: decentraland/gh-action-release@0.3.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: get latest release and export as GIT_TAG
        run:  echo "GIT_TAG=$(git tag | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" | sort -V | tail -1)" > $GITHUB_ENV
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install node dependencies
        run: yarn install
      - name: NPM Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: 'https://registry.npmjs.org'
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
